# Generated by Django 5.0.6 on 2024-07-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('analysis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='dreams.dream')),
            ],
        ),
    ]
